###get albums
GET http://localhost:9090/api/albums/

### post new album
POST http://localhost:9090/api/albums/add
Content-Type: application/json

{
    "name" : "Stamina,",
    "listIdMusics" : [],
    "idCreator" : 1,
    "image64" : "exempleDeStringEncoderEnB64",
    "image64Name" : "exemple.png"
}