### get user list
GET http://localhost:9090/users/

### post a new user
POST http://localhost:9090/users/register
Content-Type: application/json

{
    "username" : "guest@gmail.com",
    "pseudo" : "guest",
    "password" : "azerty"
}